## Favorite Vacation Spots

## Airnb Rentals in Palm Springs, California

The dataset includes property name, # beds, # bathrooms, price, and more. Each property will have an entry for each price found for it and so a single property may have multiple entries.

In [2]:
import pandas as pd 

Vacation_df = pd.read_csv('PSvacationrentals.csv')
Vacation_df.columns

Index(['city', 'country', 'dateAdded', 'dateUpdated', 'deposit',
       'descriptions', 'features', 'fees', 'languages', 'lat', 'long', 'name',
       'numBathroom', 'numBedroom', 'numBed', 'numPeople', 'people',
       'petPolicy', 'prices.dateSeen', 'prices.dateValidEnd',
       'prices.dateValidStart', 'prices.minStay', 'prices.period',
       'prices.price', 'province', 'rules'],
      dtype='object')

In [44]:
Vacation_df.shape

(11374, 26)

In [45]:
Vacation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11374 entries, 0 to 11373
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   11374 non-null  object
 1   country                11370 non-null  object
 2   dateAdded              11374 non-null  object
 3   dateUpdated            11374 non-null  object
 4   deposit                285 non-null    object
 5   descriptions           10377 non-null  object
 6   features               8581 non-null   object
 7   fees                   6719 non-null   object
 8   languages              8 non-null      object
 9   lat                    11337 non-null  float64
 10  long                   11337 non-null  float64
 11  name                   11372 non-null  object
 12  numBathroom            11365 non-null  object
 13  numBedroom             11374 non-null  int64
 14  numBed                 1647 non-null   float64
 15  numPeople              11374 non-null  object
 16  people                 7412 non-null   object
 17  petPolicy              18 non-null     object
 18  prices.dateSeen        10621 non-null  object
 19  prices.dateValidEnd    240 non-null    object
 20  prices.dateValidStart  240 non-null    object
 21  prices.minStay         9941 non-null   object
 22  prices.period          10318 non-null  object
 23  prices.price           10621 non-null  object
 24  province               11374 non-null  object
 25  rules                  1366 non-null   object
dtypes: float64(3), int64(1), object(22)
memory usage: 2.3+ MB

In [46]:
Vacation_df.isnull().sum().sort_values(ascending=False)

languages                11366
petPolicy                11356
prices.dateValidStart    11134
prices.dateValidEnd      11134
deposit                  11089
rules                    10008
numBed                    9727
fees                      4655
people                    3962
features                  2793
prices.minStay            1433
prices.period             1056
descriptions               997
prices.price               753
prices.dateSeen            753
lat                         37
long                        37
numBathroom                  9
country                      4
name                         2
province                     0
city                         0
numPeople                    0
dateUpdated                  0
dateAdded                    0
numBedroom                   0
dtype: int64

In [47]:
Vacation_df.head()

,city,country,dateAdded,dateUpdated,deposit,descriptions,features,fees,languages,lat,...,people,petPolicy,prices.dateSeen,prices.dateValidEnd,prices.dateValidStart,prices.minStay,prices.period,prices.price,province,rules
0,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,28-Dec-15,24-Dec-15,4 nights,Weekly,USD 3300,CA,NaN
1,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,3-Jan-16,30-Dec-15,3 nights,Weekly,USD 3200,CA,NaN
2,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,28-Dec-15,24-Dec-15,4 nights,Weeknight,USD 525,CA,NaN
3,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,3-Jan-16,30-Dec-15,3 nights,Weeknight,USD 500,CA,NaN
4,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,"2016-01-21T00:00:00Z, 2016-01-03T00:00:00Z, 20...",31-May-16,4-Jan-16,1 night,Weekly,USD 2499,CA,NaN

In [48]:
Vacation_df

,city,country,dateAdded,dateUpdated,deposit,descriptions,features,fees,languages,lat,...,people,petPolicy,prices.dateSeen,prices.dateValidEnd,prices.dateValidStart,prices.minStay,prices.period,prices.price,province,rules
0,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,28-Dec-15,24-Dec-15,4 nights,Weekly,USD 3300,CA,NaN
1,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,3-Jan-16,30-Dec-15,3 nights,Weekly,USD 3200,CA,NaN
2,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,28-Dec-15,24-Dec-15,4 nights,Weeknight,USD 525,CA,NaN
3,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,2015-12-18T00:00:00Z,3-Jan-16,30-Dec-15,3 nights,Weeknight,USD 500,CA,NaN
4,Palm Springs,US,2015-09-24T17:09:30Z,2016-03-17T23:06:02Z,NaN,This unique home is a combination of Zen and M...,NaN,"[{""amount"":""USD 50 / stay"",""type"":""Pet""},{""amo...",NaN,33.838097,...,"[{""dateSeen"":""2016-01-03T00:00:00Z"",""name"":""Ab...",NaN,"2016-01-21T00:00:00Z, 2016-01-03T00:00:00Z, 20...",31-May-16,4-Jan-16,1 night,Weekly,USD 2499,CA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11369,Palm Springs,US,2016-08-02T21:17:40Z,2016-08-02T21:17:40Z,NaN,"[{""value"":""Air Conditioning Ceiling Fans Centr...","[{""key"":""Pets Allowed"",""value"":""Ask""},{""key"":""...","[{""amount"":""USD 237 / stay"",""type"":""Pool/spa h...",NaN,33.839370,...,NaN,NaN,2016-07-31T00:00:00Z,NaN,NaN,3 nights,Weeknight,USD 895,CA,NaN
11370,Palm Springs,US,2016-08-02T21:17:40Z,2016-08-02T21:17:40Z,NaN,"[{""value"":""Air Conditioning Ceiling Fans Centr...","[{""key"":""Pets Allowed"",""value"":""Ask""},{""key"":""...","[{""amount"":""USD 237 / stay"",""type"":""Pool/spa h...",NaN,33.839370,...,NaN,NaN,2016-07-31T00:00:00Z,NaN,NaN,2 nights,Weeknight,USD 495,CA,NaN
11371,Palm Springs,US,2016-08-02T21:17:40Z,2016-08-02T21:17:40Z,NaN,"[{""value"":""Air Conditioning Ceiling Fans Centr...","[{""key"":""Pets Allowed"",""value"":""Ask""},{""key"":""...","[{""amount"":""USD 237 / stay"",""type"":""Pool/spa h...",NaN,33.839370,...,NaN,NaN,2016-07-31T00:00:00Z,NaN,NaN,5 nights,Weeknight,USD 1295,CA,NaN
11372,Palm Springs,US,2016-08-02T21:17:40Z,2016-08-02T21:17:40Z,NaN,"[{""value"":""Air Conditioning Ceiling Fans Centr...","[{""key"":""Pets Allowed"",""value"":""Ask""},{""key"":""...","[{""amount"":""USD 237 / stay"",""type"":""Pool/spa h...",NaN,33.839370,...,NaN,NaN,2016-07-31T00:00:00Z,NaN,NaN,4 nights,Weeknight,USD 995,CA,NaN
11373,Downtown Palm Springs Vacation Rentals,US,2016-04-09T02:45:26Z,2016-04-14T12:07:41Z,NaN,La Casa Del Sol (The House of Sun) in Rancho M...,NaN,NaN,NaN,33.760593,...,"[{""dateSeen"":""2016-04-12T00:00:00Z"",""name"":""Mc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,CA,NaN